
name: Component1 Build and Push To DockerHub


on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker_Hub Login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run:  |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - name: Build Docker Image
      run:  docker build  ./Component2_Code --tag sondos2002/component2
      
    - name: Docker Push
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/component2
      
   
    
      
        
    
    
